<a href="https://colab.research.google.com/github/mdzaeem/100-days-of-machine-learning/blob/main/Label_%26_Ordinal_Encounter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df =pd.read_csv("/content/customer_data.csv")

In [ ]:
df.shape

(100000, 11)

In [ ]:
df.set_index('id', inplace=True)

In [ ]:
df.sample(10)

id  age  gender   income education region loyalty_status  \
50803  50804   34  Female  20056.0  Bachelor  South         Silver   
62666  62667   25    Male  32845.0   College  South        Regular   
45819  45820   38  Female  28875.0   College   West         Silver   
73800  73801   34  Female  19983.0  Bachelor  North         Silver   
83894  83895   34    Male  15220.0   Masters  South         Silver   
27640  27641   23    Male  10993.0   College   East        Regular   
27144  27145   21    Male  30813.0   College   West        Regular   
50851  50852   32    Male   9255.0   College   East           Gold   
77544  77545   24  Female  35736.0  Bachelor   West        Regular   
49413  49414   30    Male  16473.0   College  North        Regular   

      purchase_frequency  purchase_amount product_category  promotion_usage  \
50803               rare           6839.0         Clothing              0.0   
62666         occasional          12105.0           Health              1.0   
45819               rare          11726.0            Books              0.0   
73800           frequent           6231.0         Clothing              0.0   
83894           frequent           5396.0      Electronics              0.0   
27640         occasional           3828.0           Health              0.0   
27144               rare          11972.0         Clothing              0.0   
50851               rare           3004.0         Clothing              0.0   
77544               rare          12066.0             Home              0.0   
49413               rare           6546.0             Food              0.0   

       satisfaction_score  
50803                 6.0  
62666                 3.0  
45819                 5.0  
73800                 5.0  
83894                 4.0  
27640                 3.0  
27144                 4.0  
50851                 6.0  
77544                 6.0  
49413                 4.0

In [ ]:
x=df["loyalty_status"].value_counts()
print(x)

loyalty_status
Regular    55224
Silver     27556
Gold        9097
Name: count, dtype: int64


In [ ]:
df1=df[["gender","education","loyalty_status"]]

In [ ]:
df1.drop_duplicates(inplace=True)
df1.dropna(axis=1)

<ipython-input-38-97cc7a20df65>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop_duplicates(inplace=True)


Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 6, 7, 8, 12, 13, 15, 16, 33, 39, 52, 56, 62, 65, 75, 95, 140, 143, 152, 180, 91877]

In [ ]:
df1=df1.head(10)

In [ ]:
df1

gender   education loyalty_status
0     Male    Bachelor           Gold
1     Male     Masters        Regular
2     Male    Bachelor         Silver
3     Male  HighSchool        Regular
4   Female     College        Regular
6   Female    Bachelor         Silver
7   Female  HighSchool        Regular
8     Male     College        Regular
12    Male     College         Silver
13  Female    Bachelor        Regular

In [ ]:
from sklearn.model_selection import train_test_split
# X_train,X_test,y_train,_y_test=train_test_split(df1.drop("loyalty_status", axis=1),df1["loyalty_status"],test_size=0.3, random_state=0)

X_train,X_test,y_train,_y_test=train_test_split(df1.iloc[:,0:2],df1.iloc[:,-1],test_size=0.3, random_state=0)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[["Male","Female"],["HighSchool","College","Bachelor","Masters"]])
oe.fit(X_train)
# oe.fit(y_train)
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [ ]:
X_test

array([[0., 2.],
       [0., 1.],
       [1., 1.]])

In [ ]:
y_train

13    Regular
1     Regular
7     Regular
8     Regular
3     Regular
0        Gold
6      Silver
Name: loyalty_status, dtype: object

In [ ]:
y_test

array([2, 2, 1])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit(y_train)
y_train=le.transform(y_train)
y_test=le.transform(_y_test)

In [ ]:
y_train

array([1, 1, 1, 1, 1, 0, 2])

In [ ]:
y_test

array([2, 2, 1])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype 
---  ------              --------------   ----- 
 0   id                  100000 non-null  int64 
 1   age                 100000 non-null  int64 
 2   gender              100000 non-null  object
 3   income              100000 non-null  int64 
 4   education           100000 non-null  object
 5   region              100000 non-null  object
 6   loyalty_status      100000 non-null  object
 7   purchase_frequency  100000 non-null  object
 8   purchase_amount     100000 non-null  int64 
 9   product_category    100000 non-null  object
 10  promotion_usage     100000 non-null  int64 
 11  satisfaction_score  100000 non-null  int64 
dtypes: int64(6), object(6)
memory usage: 9.2+ MB


In [ ]:
df.isnull().sum()

id                    0
age                   0
gender                0
income                0
education             0
region                0
loyalty_status        0
purchase_frequency    0
purchase_amount       0
product_category      0
promotion_usage       0
satisfaction_score    0
dtype: int64

In [ ]:
df.duplicated().sum()

0

In [ ]:
plt.bar(x=df['education'],y=df['purchase_frequency'])

TypeError: bar() missing 1 required positional argument: 'height'